version: '3.7'

services:
  react-app:
    build: .
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./react-app/:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    container_name: react-app

volumes:
  node_modules: