version: '3.5'

services:
  frontend:
    image: frontend
    build: ml-kurkkumopo-frontend/.
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://127.0.0.1:5000
    container_name: frontend
    command: serve -s -l 3000 build
    depends_on:
      - backend

  backend:
    image: backend
    build: ml-kurkkumopo-backend/.
    ports:
      - 5000:5000
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
    volumes:
      - model:/src/model
    container_name: backend
    command: python -u app.py
    depends_on:
      - training

  training:
    image: training
    build: ml-kurkkumopo-training/.
    volumes:
      - ./imgs:/src/imgs
      - model:/src/model
    container_name: training
    command: python -u train.py

volumes:
  model: