version: '3.5'

services:
    simple-web-service:
      image: devopsdockeruh/simple-web-service
      build: .
      ports:
        - 8080:8080
      container_name: sws-browser
      command: server