version: '3.5'

services:
  frontend:
    image: frontend-example/ruikawahara
    build: ../example-frontend
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://127.0.0.1:8080
    container_name: frontend
    command: serve -s -l 5000 build
    depends_on:
      - redis

  backend:
    image: backend-example/ruikawahara
    build: ../example-backend
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=bird
    container_name: backend
    command: ./server

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ~/cache:/data
    container_name: redis
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped 
    environment:
      - POSTGRES_PASSWORD=bird
    volumes:
      - ~/database:/var/lib/postgresql/data
    container_name: db_backend
    depends_on:
      - backend