version: '3.5'

services:
  frontend:
    image: ruikawahara/frontend-devops-w-docker:latest
    # build: ../../example-frontend # use this and comment above if you want to use my Dockerfile
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost
    container_name: frontend
    command: serve -s -l 5000 build
    depends_on:
      - redis

  backend:
    image: ruikawahara/backend-devops-w-docker
    # build: ../../example-backend # use this and comment above if you want to use my Dockerfile
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=bird
    container_name: backend
    command: ./server

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - cache:/data 
    container_name: redis
    depends_on:
      - db_backend

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped 
    environment:
      - POSTGRES_PASSWORD=bird
    volumes:
      - database:/var/lib/postgresql/data
    container_name: db_backend
    depends_on:
      - backend

  proxy:
    image: nginx:1.21
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    environment:
      - NGINX_HOST=http://localhost
      - NGINX_PORT=80
    container_name: proxy
    depends_on:
      - frontend

volumes:
  database:
  cache: